Provide a patched Mitsuba kernel pypi package suitable for Eradiate [1/2]
eradiate/mitsuba3 pull request #2
Opened 2023-05-04 12:55 UTC by wint3ria

## Description

Eradiate uses a set of specific Mitsuba variants and implements a few Mitsuba plugins for its functionalities. As a result, the default mitsuba pypi package provided by the RGL is not suitable for the Eradiate workflow. The Eradiate team has thus decided to release both an Eradiate and an [Eradiate Mitsuba](https://pypi.org/project/eradiate-mitsuba/#description) pypi packages. This PR aims at implementing the later one, which includes:
- A Mitsuba kernel with suitable variants compiled for Eradiate
- The Eradiate specific plugins builtin the binary
- A versioning system designed to distinguish the upstream Mitsuba version from the package version and the patch version.

### Compilation configuration

The Eradiate compilation configuration is provided through a CMakePresets.json file at the root. The preset is called `eradiate`.
The preset sets the `MI_DEFAULT_VARIANTS` variable to select the variants:
- scalar_mono
- scalar_mono_double
- scalar_rgb
- scalar_spectral
- llvm_rgb

It also disables embree support due to the inability of the lib to support double precision computations necessary for Eradiate. Thus the variable `MI_ENABLE_EMBREE` is set to `OFF`.

### Eradiate plugins

Eradiate plugins have been added from the main Eradiate repository to the `src/eradiate_plugins` directory. The CMake configuration has been updated to include these plugins accordingly.

A slight modification has been made to the `sphericalcoordsvolume` involving renaming a generated using statement manually instead of generating it using [`MI_IMPORT_TYPES`](https://mitsuba.readthedocs.io/en/stable/src/developer_guide/writing_plugin.html#mi-import-types), in order to support the compilation with GCC. The problem here is related to how GCC (doesn't) work, and is not related to any specific issue with the `MI_IMPORT_TYPES` preprocessing macro.

### Versioning

### CI/CD

## Note: documentation

This PR is the first out of 2 patches for the Eradiate Mitsuba engine. The second PR in this regard will focus on the documentation of the features described here and shall provide:
- An updated description and long description of the wheels for pypi
- Documentation of the versioning schema
- Documentation of the build process
- Documentation of the picked variants
- Documentation of the plugins

## Testing

Compilation logs [here](todo)
TODO: pip install output
TODO: 

## Checklist

- [ ] My code follows the [style guidelines](https://mitsuba.readthedocs.io/en/latest/src/developer_guide.html#coding-style) of this project
- [ ] My changes generate no new warnings
- [ ] My code also compiles for `cuda_*` and `llvm_*` variants. If you can't test this, please leave below
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I cleaned the commit history and removed any "Merge" commits
- [ ] I give permission that the Mitsuba 3 project may redistribute my contributions under the terms of its [license](https://github.com/mitsuba-renderer/mitsuba/blob/master/LICENSE)

2023-05-04 14:51 UTC, wint3ria commented
I think I'm ready for a first round of review @leroyvn . I don't think we should merge this with the main yet, I would like to implement the support for this in Eradiate to have a better validation of all the functionalities

2023-05-04 22:47 UTC, leroyvn reviewed
Hi @wint3ria, thanks for this detailed PR. Since we agreed on most points, we're pretty much ready to go with this. Just a question: you write

> The wheels action passes the github ref in the MI_PKG_VERSION to automatically use a version tag.

Doesn't this contradict the in-code version sourcing we eventually decided to go for?

Another thing: are you planning to move plugin tests here as part of this PR or another one?

2023-05-04 22:47 UTC, leroyvn commented on CMakePresets.json
> +}
Newline at EOF:
```suggestion
}

```

2023-05-04 22:47 UTC, leroyvn commented on src/eradiate_plugins/CMakeLists.txt
> +set(MI_PLUGIN_TARGETS "${MI_PLUGIN_TARGETS}" PARENT_SCOPE)
```suggestion
set(MI_PLUGIN_TARGETS "${MI_PLUGIN_TARGETS}" PARENT_SCOPE)

```

2023-05-05 08:12 UTC, wint3ria commented
> > The wheels action passes the github ref in the MI_PKG_VERSION to automatically use a version tag.
> 
> Doesn't this contradict the in-code version sourcing we eventually decided to go for?
Not really. The idea here is to have access to the patch version in some way. It does not matter if it's inside the header or on the package version.

In practice I don't see a good reason to tag meaningless refs, nor to avoid tagging even a minor release. In practice the header version should be in sync with the tags and the package most of the time. Discrepencies between versions may arise from dev/test/custom environments made by develepers, and can be detected anyway

I do see the use case of being able to test the upload of the package using different versions though. For instance, just for developing the current PR, I made multiple rcs that I eventually dropped. It's just very convenient to be able to override the version when working on the packages themselves.

I made the choice to leave the mitsuba version as detected by setuptools to the mitsuba kernel upstream version. To the best of my knowledge, conditional code involving the version should only be present in the compiled code. So it could be possible to use our own kernel version instead if you prefer so that `import mitsuba; mitsuba.__version__` gives `0.0.1`

2023-05-05 08:15 UTC, wint3ria commented
> Another thing: are you planning to move plugin tests here as part of this PR or another one?
Plugin tests? 🙃

2023-05-05 08:27 UTC, wint3ria commented
Ok I'll add an additional commit on this PR for the plugin tests.

I'd like to move on with the next feature for the eradiate packaging though, as the schedule is short. Since a package is already available, and the plugin tests are plain python, I can decouple these two tasks and test the plugins in eradiate for now. I already have internal work scheduled right after the 9th of June, thus I may come back to this PR in July, or if I have a hole at some point.

2023-05-10 12:07 UTC, wint3ria commented
I took some time for the plugin which tests are now committed :)

2023-05-10 12:47 UTC, wint3ria commented
It think this is ready for merging into packaging, a new branch in our mitsuba codebase that we could rebase on the branch upstream/master anytime we pull from the later

2023-05-15 14:39 UTC, leroyvn requested changes
Hi @wint3ria, this looks good. Just a few comments and changes and we can merge.

2023-05-15 14:39 UTC, leroyvn commented on src/eradiate_plugins/tests/conftest.py
I don't think you need this file at all: the `src` directory already contains all these definitions.

2023-05-15 14:39 UTC, leroyvn commented on src/eradiate_plugins/tests/__init__.py
The Mitsuba test sutie has no `__init__.py`. I suggest to remove them in our code as well. AFAIK the main reason to have them is to minimize the risk of test name clashes: we can simply stick to Mitsuba's test name convention for safety.

2023-06-15 15:09 UTC, merged